[package]
name = "rpncalc"
version = "0.1.0"
authors = ["hu3d4 <66501033+hu3d4@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
clap = "3.0.0-beta.2"
thiserror = "1.0.22"
